version: "3"

services:
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: BankAtmODS
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5832:5432"
    pgadmin:
        image: dpage/pgadmin4:5.6
        environment:
            PGADMIN_DEFAULT_EMAIL: winston@govansnv.com
            PGADMIN_DEFAULT_PASSWORD: teSt123456@!
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 15432:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - database

volumes:
    postgres:
    pgadmin: